//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCClientsApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public string IdentityNumber { get; set; }
        public string Surname { get; set; }
        public string Firstname { get; set; }
        public Nullable<System.Guid> IdentityTypeId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
    
        public virtual IdentityType IdentityType { get; set; }
    }
}
